### PR TITLE
Added `dockerNetwork` property

### LINKED ISSUE #29: Set network in docker build command
Is it possible to set the `--network` option/property in the `docker build` command?

I'm running semantic-release in a GitLab CI that's running Docker in Docker. Part of the build process requires downloading other dependencies from package managers.

### PR DESCRIPTION
**Pull request by sambunting**
I've added a `dockerNetwork` policy to allow the user to define which Docker network to use when the image is being built.

You would use it alongside the standard plugin configuration - and by default, the value of `dockerNetwork` is "default", as this is the default value for the `--network` flag for `docker build`.

This fixes #29

### CODE REVIEW

**Comment by brennerm** [comment]
@esatterwhite Is there any way I can help getting this merged? Would really like to use it.

**Comment by esatterwhite** [comment]
Sorry, I lost track of this. will take a look today

**Review by esatterwhite — APPROVED** [review]

**Comment by esatterwhite** [comment]
It looks like your branch was a bit out of date. I'm going to have fix this up the old fashioned way. Should have a release with this change in an hour or so

**Comment by brennerm** [comment]
Awesome, huge thanks @sambunting @esatterwhite

**Comment by esatterwhite** [comment]
v4.2.0 is up and should have these changes. Very interested to see if it works as expected. I was having a bit of trouble with this in github actions, but I think it was a docker-in-docker problem

**Comment by brennerm** [comment]
Works like a charm, huge thanks!

**Pull request merged**
